source 'http://rubygems.org'

gem 'rails', '~> 4.0.0'
gem 'sqlite3'

gem 'json'
gem 'haml'
gem 'haml-rails'
gem 'jquery-rails'
gem 'jquery-ui-rails'

gem 'awesome_nested_set'
gem 'the_sortable_tree', path: '../../'

group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
  gem 'faker'
end