source 'http://rubygems.org'

gem 'rails', '~> 4.1.0'
gem 'sqlite3'

gem 'json'
gem 'haml'
gem 'haml-rails'
gem 'jquery-rails'
gem 'jquery-ui-rails'

gem 'quiet_assets'

gem 'awesome_nested_set', github: "collectiveidea/awesome_nested_set"
gem 'ancestry', github: "stefankroes/ancestry"
gem 'acts_as_list', github: "swanandp/acts_as_list"
gem 'the_sortable_tree', path: '../../'

group :assets do
  gem 'uglifier'
  gem 'sass-rails', github: "rails/sass-rails"
  gem 'coffee-rails'
end

group :development, :test do
  gem 'faker'
  gem 'pry'

  gem 'rspec'
  gem 'rspec-core'
  gem 'rspec-rails'
  gem 'rspec-mocks'
  gem 'rspec-expectations'

  gem 'capybara'
  gem 'selenium-webdriver'
end

group :test do
  gem 'factory_girl'
  gem 'database_cleaner'
end
